### ISSUE TITLE
Localization crash

### ISSUE THREAD

**Issue by baarkerlounger** [blissd/fotema#66]
```bash
$ flatpak run app.fotema.Fotema

thread 'main' panicked at src/languages.rs:67:10: Localization files should be present: RequestedLanguagesEmpty note: run with \`RUST_BACKTRACE=1\` environment variable to display a backtrace
```

**Comment by blissd** [comment]
Thank  you for your bug report. I can reproduce the problem on my system by overriding the `LANG` environment variable to be blank.

```shell
LANG="" flatpak run app.fotema.Fotema
thread 'main' panicked at src/languages.rs:67:10:
Localization files should be present: RequestedLanguagesEmpty
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'll work on a fix, but in the meantime as a workaround  you can specify the language when running Fotema:

```shell
LANG=en flatpak run app.fotema.Fotema
```

**Comment by blissd** [comment]
Fixed in 1.8.4 which is now available on Flathub.
